language: ruby
sudo: false
cache: bundler
script: bundle exec rake spec
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.0
  - jruby
  - jruby-head
  - rbx-2
jdk:
  - openjdk7
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: jruby-head
    - rvm: rbx-2
